export type MostLikelyMode = "normal" | "spicy" | "deep";

export const mostLikelyNormal = [
  "Chi è più probabile che arrivi sempre in ritardo?",
  "Chi è più probabile che organizzi una vacanza all'ultimo secondo?",
  "Chi è più probabile che dimentichi perché è entrato in una stanza?",
  "Chi è più probabile che scelga il ristorante e poi ordini sempre la stessa cosa?",
  "Chi è più probabile che perda il telefono mentre lo sta usando?",
  "Chi è più probabile che inizi una serie e la finisca in una notte?",
  "Chi è più probabile che trasformi una commissione veloce in un'avventura?",
  "Chi è più probabile che canti senza sapere metà delle parole?",
  "Chi è più probabile che faccia amicizia con chiunque in cinque minuti?",
  "Chi è più probabile che compri qualcosa solo perché era in offerta?",
  "Chi è più probabile che abbia una playlist per ogni situazione?",
  "Chi è più probabile che si perda anche con il navigatore acceso?",
  "Chi è più probabile che dica 'arrivo' quando deve ancora uscire?",
  "Chi è più probabile che faccia ridere tutti senza volerlo?",
  "Chi è più probabile che proponga una cena e poi non sappia dove andare?",
  "Chi è più probabile che tenga mille schede aperte sul telefono?",
  "Chi è più probabile che mandi vocali lunghissimi?",
  "Chi è più probabile che faccia una foto a ogni piatto?",
  "Chi è più probabile che si dimentichi il compleanno di qualcuno?",
  "Chi è più probabile che inventi una scusa credibile sul momento?",
  "Chi è più probabile che cambi programma tre volte nella stessa sera?",
  "Chi è più probabile che trovi sempre il lato comico delle cose?",
  "Chi è più probabile che parta per un weekend senza avvisare nessuno?",
  "Chi è più probabile che diventi competitivo in un gioco semplice?",
] as const;

export const mostLikelySpicy = [
  "Chi è più probabile che mandi un messaggio rischioso alle 2 di notte?",
  "Chi è più probabile che abbia una cotta segreta?",
  "Chi è più probabile che flirti senza accorgersene?",
  "Chi è più probabile che faccia il primo passo con grande naturalezza?",
  "Chi è più probabile che abbia un debole per qualcuno che non dovrebbe?",
  "Chi è più probabile che arrossisca quando viene guardato troppo a lungo?",
  "Chi è più probabile che lasci intendere più di quanto dica?",
  "Chi è più probabile che riceva attenzioni senza rendersene conto?",
  "Chi è più probabile che sappia creare tensione con una sola frase?",
  "Chi è più probabile che abbia una chat che non farebbe leggere a tutti?",
  "Chi è più probabile che venga conquistato da uno sguardo?",
  "Chi è più probabile che faccia finta di niente quando gli piace qualcuno?",
  "Chi è più probabile che sia più romantico di quanto ammetta?",
  "Chi è più probabile che abbia avuto un colpo di fulmine?",
  "Chi è più probabile che faccia un complimento che resta in testa?",
  "Chi è più probabile che sappia sedurre senza sembrare interessato?",
  "Chi è più probabile che si lasci trascinare da una serata speciale?",
  "Chi è più probabile che abbia un fascino difficile da spiegare?",
  "Chi è più probabile che mandi un messaggio e poi si penta subito?",
  "Chi è più probabile che tenga nascosta una simpatia per settimane?",
  "Chi è più probabile che capisca subito quando due persone si piacciono?",
  "Chi è più probabile che giochi con lo sguardo più che con le parole?",
  "Chi è più probabile che riceva un invito inaspettato?",
  "Chi è più probabile che sembri innocente ma non lo sia del tutto?",
] as const;

export const mostLikelyDeep = [
  "Chi è più probabile che nasconda quando sta male?",
  "Chi è più probabile che abbia cambiato molto senza dirlo?",
  "Chi è più probabile che ascolti davvero gli altri?",
  "Chi è più probabile che ricordi dettagli che gli altri dimenticano?",
  "Chi è più probabile che dia consigli sinceri anche quando sono scomodi?",
  "Chi è più probabile che protegga il gruppo senza farsi notare?",
  "Chi è più probabile che abbia una storia che pochi conoscono?",
  "Chi è più probabile che sembri leggero ma senta tutto molto intensamente?",
  "Chi è più probabile che capisca quando qualcuno non sta bene?",
  "Chi è più probabile che abbia imparato molto da un periodo difficile?",
  "Chi è più probabile che faccia fatica a chiedere aiuto?",
  "Chi è più probabile che si prenda cura degli altri prima di sé?",
  "Chi è più probabile che abbia sogni grandi ma li racconti poco?",
  "Chi è più probabile che perdoni anche quando non dovrebbe?",
  "Chi è più probabile che cambi idea dopo aver ascoltato davvero?",
  "Chi è più probabile che noti il lato buono delle persone?",
  "Chi è più probabile che tenga insieme il gruppo nei momenti strani?",
  "Chi è più probabile che abbia paura di deludere gli altri?",
  "Chi è più probabile che sembri forte anche quando è stanco?",
  "Chi è più probabile che faccia una scelta coraggiosa in silenzio?",
  "Chi è più probabile che conosca bene i propri limiti?",
  "Chi è più probabile che abbia bisogno di più tempo per fidarsi?",
  "Chi è più probabile che dica la cosa giusta al momento giusto?",
  "Chi è più probabile che sorprenda tutti mostrando un lato nuovo?",
] as const;

export const mostLikelyQuestions: Record<MostLikelyMode, readonly string[]> = {
  normal: mostLikelyNormal,
  spicy: mostLikelySpicy,
  deep: mostLikelyDeep,
};
