export type TruthOrDareMode = "friends" | "spicy";
export type TruthOrDarePromptType = "truth" | "dare";

export const truthOrDarePrompts: Record<
  TruthOrDareMode,
  Record<TruthOrDarePromptType, string[]>
> = {
  friends: {
    truth: [
      "Qual e l'ultima cosa che hai cercato di nascondere a un amico?",
      "Qual e la figuraccia che ti fa ancora ridere ripensandoci?",
      "Chi del gruppo chiameresti per primo se avessi un problema serio?",
      "Qual e la cosa piu impulsiva che hai fatto quest'anno?",
      "Qual e la bugia bianca che dici piu spesso?",
      "Qual e il complimento che ti ha fatto piu effetto?",
      "Che abitudine strana hai e pensi che quasi nessuno conosca?",
      "Quando ti sei sentito davvero fiero di te l'ultima volta?",
      "Qual e la tua mania piu inutile ma a cui non rinunci?",
      "Che cosa rimandi da troppo tempo e sai che dovresti fare?",
      "Qual e il messaggio che hai scritto e poi cancellato senza inviarlo?",
      "Che cosa ti annoia subito anche se piace a tutti?",
      "Qual e la cosa piu coraggiosa che hai fatto per uscire dalla routine?",
      "Che cosa ti mette subito di buon umore?",
      "Qual e il ricordo scolastico che ti rappresenta di piu?",
      "Con chi faresti un viaggio improvvisato domani mattina?",
      "Qual e il tuo talento piu sottovalutato?",
      "Che cosa fai quando vuoi sembrare piu sicuro di quanto sei davvero?",
      "Qual e il consiglio migliore che hai ricevuto da un amico?",
      "Che scelta piccola ha cambiato molto la tua settimana di recente?",
      "Qual e la cosa piu inutile che hai comprato e hai comunque amato?",
      "Qual e il tuo comfort movie o comfort song per eccellenza?",
      "Quando hai cambiato idea su qualcosa di importante?",
      "Qual e il posto dove torni sempre volentieri?",
    ],
    dare: [
      "Imita qualcuno del gruppo per 20 secondi senza dire chi e.",
      "Manda un vocale di 10 secondi con il tono piu teatrale che riesci a fare.",
      "Fai una passerella improvvisata per tutta la stanza.",
      "Parla con accento inventato fino al tuo prossimo turno.",
      "Racconta una storia banalissima come se fosse un trailer epico.",
      "Scegli una persona e falle un complimento molto specifico.",
      "Canta il ritornello di una canzone che tutti conoscono.",
      "Fingi di essere un motivatore professionista per 15 secondi.",
      "Fai tre pose da copertina senza ridere.",
      "Descrivi il gruppo come se fosse una serie tv.",
      "Scatta un selfie serio come se fossi su una rivista di moda.",
      "Fai un brindisi improvvisato dedicato alla serata.",
      "Leggi l'ultimo messaggio ricevuto con voce da documentario.",
      "Inventati uno slogan per la persona seduta alla tua destra.",
      "Fai cinque secondi di dance challenge senza musica.",
      "Parla al rallentatore fino al turno successivo.",
      "Recita il menu di una pizzeria come se fossi sul palco.",
      "Fai una dichiarazione d'amicizia super drammatica a qualcuno del gruppo.",
      "Prova a far ridere tutti in meno di 15 secondi.",
      "Scegli un oggetto vicino e vendilo come se fossi in tv.",
      "Fai finta di rispondere a una chiamata importantissima.",
      "Imita il modo di camminare di un personaggio famoso.",
      "Fai una mini coreografia di tre movimenti e insegnala a tutti.",
      "Parla di te in terza persona fino al turno successivo.",
    ],
  },
  spicy: {
    truth: [
      "Chi del gruppo trovi piu magnetico in questo momento?",
      "Qual e la qualita che ti fa crollare subito per qualcuno?",
      "Qual e stata la situazione piu intensa che hai vissuto di recente?",
      "Che tipo di messaggio ti fa sorridere appena lo leggi?",
      "Qual e il complimento piu audace che hai ricevuto?",
      "Ti fidi piu del feeling immediato o del tempo? Perche?",
      "Qual e il segnale che ti fa capire che c'e chimica vera?",
      "Che cosa trovi irresistibile ma non dici quasi mai ad alta voce?",
      "Qual e il gesto piu affascinante che una persona possa fare?",
      "Che cosa ti incuriosisce di piu quando conosci qualcuno?",
      "Se dovessi descrivere il tuo tipo ideale in tre parole, quali useresti?",
      "Qual e il tuo red flag piu divertente da ammettere?",
      "Che cosa non perdoneresti in una frequentazione?",
      "Qual e il momento in cui ti senti piu sicuro di te?",
      "Che cosa apprezzi di piu in un flirt ben fatto?",
      "Qual e la cosa piu coraggiosa che hai fatto per seguire l'istinto?",
      "Quando hai capito di piacere davvero a qualcuno l'ultima volta?",
      "Che cosa ti fa cambiare idea in positivo su una persona?",
      "Qual e il dettaglio che noti subito quando qualcuno ti interessa?",
      "Qual e la situazione piu imbarazzante ma intensa che ricordi?",
      "Ti piace di piu provocare o essere provocato?",
      "Qual e la frase piu efficace che qualcuno potrebbe dirti al momento giusto?",
      "Cosa ti fa sentire davvero desiderato?",
      "Qual e il confine che difendi sempre anche nel gioco?",
    ],
    dare: [
      "Fai un complimento audace ma elegante a qualcuno del gruppo.",
      "Sostieni lo sguardo di una persona per 8 secondi senza ridere.",
      "Descrivi il tuo appuntamento ideale in tre dettagli concreti.",
      "Dai a qualcuno del gruppo un soprannome da date-night.",
      "Racconta il tuo lato piu affascinante in una frase sola.",
      "Scegli una persona e dille quale dettaglio noteresti subito di lei.",
      "Parla con tono da film romantico fino al turno successivo.",
      "Fai una camminata lenta e sicura come se stessi entrando a una festa esclusiva.",
      "Dedica il titolo di una canzone a qualcuno del gruppo e spiega perche.",
      "Racconta il tuo appuntamento perfetto in massimo 15 secondi.",
      "Presentati come se fossi il protagonista di un trailer romantico.",
      "Invia un complimento sincero a qualcuno fuori dal gruppo.",
      "Ricrea per cinque secondi il tuo miglior ingresso in slow motion.",
      "Scegli una persona e brindale con una frase elegante.",
      "Fai finta di ricevere un invito irresistibile e reagisci dal vivo.",
      "Descrivi con una parola l'energia di ciascuno, solo in positivo.",
      "Recita una frase banalissima come se fosse indimenticabile.",
      "Scegli una persona e dille quale tipo di energia trasmette.",
      "Racconta il tuo green flag migliore senza falsa modestia.",
      "Fingi di essere alla scena finale di una serie romantica.",
      "Lancia un brindisi dedicato alla chimica giusta.",
      "Rivela la tua miglior opening line, anche se non l'hai mai usata.",
      "Scegli qualcuno e descrivi il date perfetto con lui o lei in una frase.",
      "Fai un invito immaginario a una persona del gruppo con stile.",
    ],
  },
};
