export type TruthOrDareMode = "normal" | "spicy";
export type TruthOrDarePromptType = "truth" | "dare";

export const truthNormal = [
  "Qual è la cosa che ti ha reso più orgoglioso/a nella vita finora?",
  "Se potessi cambiare una sola decisione del passato, quale sarebbe?",
  "Cosa ti spaventa davvero, al di là delle cose ovvie?",
  "Qual è il tuo ricordo d'infanzia preferito?",
  "C'è qualcosa che hai sempre voluto imparare ma non hai mai iniziato?",
  "Qual è la persona che ha influenzato di più il tuo carattere?",
  "Cosa fai quando sei completamente solo/a e nessuno ti guarda?",
  "Qual è la cosa di cui vai più fiero/a di te stesso/a?",
  "Hai mai tradito la fiducia di qualcuno? Come ti ha fatto sentire?",
  "Qual è il sogno che non hai mai raccontato a nessuno?",
  "Se potessi vivere in qualsiasi epoca storica, quale sceglieresti e perché?",
  "Qual è la cosa più gentile che qualcuno abbia mai fatto per te?",
  "C'è qualcosa che rimpianti di non aver detto a qualcuno che non c'è più?",
  "Qual è il tuo più grande pregio e il tuo più grande difetto — sii onesto/a?",
  "Cosa ti fa alzare dal letto con entusiasmo la mattina?",
  "Hai mai pianto guardando un film o leggendo un libro? Quale?",
  "Se dovessi descrivere la tua infanzia con una sola parola, quale sarebbe?",
  "Qual è la cosa che più ti mette a disagio nelle situazioni sociali?",
  "C'è qualcuno con cui hai un conto in sospeso che non hai mai chiuso?",
  "Qual è la cosa che nessuno sa di te e che ti sorprenderebbe raccontare?",
  "Se potessi parlare con il tuo sé di 10 anni fa, cosa gli diresti?",
  "Qual è la tua più grande insicurezza — quella che cerchi di nascondere?",
  "Hai mai fatto qualcosa di cui ti vergogni ancora adesso? Cosa?",
  "Qual è la cosa che ti fa sentire davvero a casa?",
  "C'è un'amicizia che hai perso e che ti manca ancora?",
  "Cosa pensi davvero della tua famiglia, in modo onesto?",
  "Qual è la cosa che trovi più difficile da perdonare negli altri?",
  "Se potessi essere esperto/a in qualcosa senza sforzo, cosa sceglieresti?",
  "Qual è la tua routine segreta che non ammetteresti facilmente?",
  "Hai mai provato una sensazione di solitudine anche in mezzo alla gente?",
  "Cosa ti rende davvero felice — non la risposta che daresti in pubblico?",
  "Qual è la critica che ti hanno fatto e che, in fondo, sapevi fosse giusta?",
  "Se potessi fare un viaggio da solo/a, dove andresti e perché?",
  "Qual è la cosa che stai rimandando da troppo tempo?",
  "C'è qualcosa che hai sempre voluto chiedere a qualcuno qui presente?",
  "Qual è il tuo rapporto con il fallimento — ti spaventa o ti motiva?",
  "Hai mai mentito per proteggere qualcuno? Come è andata a finire?",
  "Qual è la cosa che ti fa sentire più vulnerabile?",
  "C'è un momento in cui ti sei sentito/a davvero libero/a — quando?",
  "Cosa pensi che gli altri vedano in te che tu fai fatica a vedere?",
  "Qual è la tua più grande dipendenza innocente — quella senza cui non riesci?",
  "Se la tua vita fosse un film, a che genere apparterrebbe?",
  "Hai mai deluso qualcuno che amavi? Come l'hai gestito?",
  "Qual è la cosa che desideri di più per il tuo futuro?",
  "C'è qualcosa che ti fa ancora arrabbiare solo a pensarci?",
  "Qual è l'abitudine che ti piacerebbe abbandonare ma non riesci?",
  "Hai mai pensato di fare una scelta di vita completamente diversa?",
  "Qual è la cosa più coraggiosa che tu abbia mai fatto?",
  "C'è qualcuno qui presente di cui hai un'opinione diversa da quello che dici?",
  "Se potessi rivivere un solo giorno della tua vita, quale sceglieresti?",
  "Quale canzone descrive meglio il tuo stato d'animo in questo periodo?",
  "Hai mai fatto una cosa completamente da solo/a che ti ha sorpreso di riuscire a fare?",
  "Cosa ti manca di più della tua infanzia?",
  "Qual è il consiglio che hai ricevuto e che non hai mai seguito, ma che forse avresti dovuto?",
  "Se potessi essere invisibile per un giorno, cosa faresti?",
  "Qual è la cosa di cui parli con poca gente ma che ti sta particolarmente a cuore?",
  "Hai mai avuto una sensazione viscerale su qualcuno che si è poi rivelata giusta?",
  "Qual è il libro, film o serie che ti ha cambiato qualcosa dentro?",
  "C'è una versione di te che avresti voluto diventare e non sei diventato/a?",
  "Cosa ti dà più fastidio delle persone in generale?",
  "Qual è la cosa che fai ancora oggi che ti fa sentire un po' bambino/a?",
  "Hai mai provato a cambiare radicalmente qualcosa di te? Come è andata?",
  "Qual è il confine che non attraverseresti mai, qualunque cosa succeda?",
  "Se potessi eliminare una cosa dalla tua vita senza conseguenze, cosa sarebbe?",
  "Qual è la persona con cui ti sentiresti più a tuo agio in un momento di crisi?",
  "C'è qualcosa che non hai mai perdonato a te stesso/a?",
  "Qual è il tuo rapporto con la solitudine — ti spaventa o la cerchi?",
  "Hai mai cambiato idea su qualcosa di importante? Cosa ti ha convinto?",
  "Qual è la cosa più spontanea che tu abbia mai fatto?",
  "Se potessi mandare una lettera a qualcuno del tuo passato, a chi la scriveresti?",
  "Qual è la cosa che ti fa ridere anche quando non dovresti?",
  "Hai mai invidiato qualcuno qui presente? Per cosa?",
  "Qual è il tuo rapporto con il denaro — ti dà sicurezza o ansia?",
  "C'è qualcosa che fai per gli altri ma che vorresti fare di più per te stesso/a?",
  "Qual è la cosa che ti ha insegnato di più una perdita nella tua vita?",
  "Se potessi scegliere un superpotere, quale sceglieresti e come lo useresti?",
  "Qual è il tuo rapporto con il giudizio degli altri — ti condiziona ancora?",
  "Hai mai detto \"sto bene\" quando non era vero? Con chi?",
  "Qual è la cosa che fai per sentirti bene quando tutto va storto?",
  "C'è qualcosa che hai capito solo dopo molto tempo che avresti voluto capire prima?",
  "Qual è la cosa che ti rende unico/a rispetto alle persone che conosci?",
  "Hai mai aiutato qualcuno in modo anonimo? Cosa hai fatto?",
  "Qual è il momento in cui ti sei sentito/a davvero amato/a senza aspettartelo?",
  "C'è qualcosa che non riesci ancora a spiegarti della tua personalità?",
  "Qual è la cosa che hai fatto per qualcuno e di cui sei davvero orgoglioso/a?",
  "Se potessi riscrivere le regole della società, da dove inizieresti?",
  "Qual è la cosa che ti spaventa dell'invecchiare?",
  "Hai mai sentito di essere nel posto sbagliato al momento sbagliato?",
  "Qual è il tuo rapporto con le aspettative degli altri su di te?",
  "C'è qualcosa che vorresti che le persone qui presenti sapessero di te?",
  "Qual è la cosa più assurda in cui hai creduto da piccolo/a?",
  "Hai mai fatto qualcosa di straordinario solo perché ne avevi voglia, senza pianificarlo?",
  "Qual è la cosa che ti fa sentire più forte quando ne hai bisogno?",
  "C'è un lato di te che mostri raramente e che vorresti mostrare di più?",
  "Qual è il complimento che ti ha colpito di più nella vita?",
  "Hai mai detto una bugia e poi scoperto che aveva fatto del bene?",
  "Qual è la cosa che trovi più difficile nell'essere un amico/a davvero presente?",
  "C'è qualcosa che hai sempre voluto fare ma a cui hai sempre trovato una scusa per non farlo?",
  "Qual è la cosa più importante che hai imparato da una relazione — romantica o amicale?",
  "Se potessi regalare a tutti una qualità che possiedi, quale daresti?",
] as const;

export const dareNormal = [
  "Racconta il ricordo più imbarazzante della tua adolescenza.",
  "Imita la persona nel gruppo che secondo te si preoccupa di più di come appare.",
  "Chiedi a ognuno nel gruppo una parola che lo descriva, poi commenta quella che ti ha sorpreso di più.",
  "Racconta un momento in cui hai fatto una figura terribile in pubblico.",
  "Chiedi a qualcuno nel gruppo un consiglio su qualcosa che stai davvero affrontando.",
  "Di' ad alta voce la cosa più strana che hai mangiato in vita tua.",
  "Fai una cosa che ti mette a disagio davanti al gruppo, anche piccola.",
  "Racconta com'eri da bambino/a in 3 parole: il gruppo vota se ci crede.",
  "Imita il tuo personaggio preferito di una serie TV per 30 secondi.",
  "Mostra la cosa più strana che hai sul telefono: foto, messaggio o app.",
  "Racconta una storia divertente in cui eri il protagonista della gaffe.",
  "Fai un discorso di 60 secondi su un argomento assurdo scelto dal gruppo.",
  "Descrivi la tua giornata tipo come se fosse la trama di un thriller.",
  "Racconta la cosa più assurda che hai fatto per risparmiare o per spendere.",
  "Chiudi gli occhi e di' cinque cose che ami delle persone qui presenti, una per ognuno.",
  "Chiedi scusa a qualcuno qui presente per qualcosa, anche piccola, che non hai mai chiarito.",
  "Racconta il sogno più strano che ricordi nei minimi dettagli.",
  "Imita come pensi che ognuno nel gruppo si comporti quando è solo a casa.",
  "Di' a ogni persona nel gruppo una cosa che ammiri di loro, senza ripeterti.",
  "Racconta la storia del tuo peggior lavoro o esperienza lavorativa.",
  "Mostra come balli quando sei completamente da solo/a e nessuno ti guarda.",
  "Racconta la cosa più coraggiosa che hai fatto nella tua vita.",
  "Fai una previsione sul futuro di ogni persona nel gruppo, sii specifico/a.",
  "Descrivi ogni persona nel gruppo come un personaggio di un film: qual è il suo ruolo?",
  "Racconta una verità scomoda su di te che solitamente eviti di dire.",
  "Chiedi al gruppo di fare una domanda che non ti hanno mai fatto e rispondi.",
  "Di' tre cose che cambieresti della tua vita se potessi ricominciare.",
  "Fai finta di essere un TED Talk speaker per 45 secondi su qualcosa che sai fare bene.",
  "Racconta il momento in cui ti sei sentito/a più fiero/a di te stesso/a.",
  "Mostra come reagiresti se vincessi alla lotteria, subito, in questo momento.",
  "Descrivi la tua persona ideale, non fisicamente ma come carattere.",
  "Racconta qualcosa di te che la maggior parte delle persone non sa.",
  "Fai finta di presentare qualcuno nel gruppo a dei tuoi genitori: come lo/la introdurresti?",
  "Racconta la tua storia con una passione o hobby che hai abbandonato.",
  "Chiedi a tutti nel gruppo cosa pensano sia il tuo difetto principale. Ascolta senza difenderti.",
  "Di' a voce alta qualcosa che solitamente pensi ma non dici mai.",
  "Imita come ognuno nel gruppo cammina o parla, gentilmente.",
  "Racconta come hai passato il momento più noioso della tua vita.",
  "Scegli qualcuno nel gruppo e digli cosa pensi lo/la renderà felice tra 10 anni.",
  "Fai una confessione innocente che non hai mai fatto al gruppo.",
  "Racconta un momento in cui hai fatto qualcosa di straordinariamente gentile in modo anonimo.",
  "Di' a ogni persona nel gruppo qual è, secondo te, la sua qualità più sottovalutata.",
  "Descrivi la tua settimana come se fosse un film: titolo, genere e finale.",
  "Racconta come sei cambiato/a negli ultimi 5 anni, una cosa che non ti aspettavi.",
  "Fai finta di registrare un podcast e intervista qualcuno nel gruppo per 2 minuti.",
  "Di' al gruppo la cosa che ti spaventa di più del futuro, senza filtri.",
  "Racconta il momento in cui hai capito di aver fatto la scelta giusta su qualcosa di importante.",
  "Imita come fai quando sei nervoso/a in una situazione sociale, esagerando.",
  "Racconta la telefonata più strana o più bella che hai mai avuto.",
  "Fai un toast dedicato a ogni persona nel gruppo, una frase per ognuno, sincera.",
  "Di' ad alta voce la cosa di cui sei più geloso/a, non in amore ma in generale.",
  "Racconta il momento in cui ti sei sentito/a più fuori posto nella tua vita.",
  "Fai finta di essere un venditore ambulante e vendi al gruppo la cosa più inutile che hai con te.",
  "Di' una bugia al gruppo: tutti devono indovinare se è vera o falsa.",
  "Racconta la storia di un'amicizia che ti ha cambiato davvero.",
  "Chiedi a ogni persona nel gruppo qual è, secondo loro, il tuo superpotere segreto.",
  "Racconta come risponderesti se ti dicessero che hai solo un anno di vita.",
  "Fai una dichiarazione ufficiale su qualcosa che non ti piace e di' perché.",
  "Imita come ti comporti quando stai cercando di fare una buona impressione.",
  "Racconta la cosa più impulsiva che hai fatto nella tua vita.",
  "Di' al gruppo qual è, secondo te, la cosa più bella di stare tutti insieme stasera.",
  "Racconta un momento in cui hai cambiato idea su qualcuno in modo radicale.",
  "Fai finta di essere un reporter e descrivi la serata come se fosse un notiziario.",
  "Chiedi a qualcuno nel gruppo un consiglio su qualcosa che rimandi da troppo tempo.",
  "Racconta il momento più epico di una vacanza che hai fatto.",
  "Di' al gruppo cosa vorresti che ricordassero di te tra 20 anni.",
  "Racconta la storia di qualcosa che hai imparato nel modo più duro possibile.",
  "Fai finta di essere un personaggio storico per 30 secondi: il gruppo indovina chi.",
  "Chiedi a ogni persona nel gruppo cosa porterebbero su un'isola deserta.",
  "Di' una cosa che ti ha detto qualcuno e che porti ancora con te.",
  "Racconta il momento in cui hai riso di più in vita tua.",
  "Fai finta di tenere un discorso al tuo matrimonio, improvvisato.",
  "Di' al gruppo qual è la cosa che non ti annoieresti mai di fare.",
  "Racconta come ti comportavi a scuola: eri secchione/a, ribelle o nel mezzo?",
  "Fai finta di essere un critico cinematografico e recensisci la serata di stasera.",
  "Di' a qualcuno nel gruppo una cosa che hai sempre voluto dirgli/le ma non hai mai trovato il momento.",
  "Racconta come ti vedi tra 10 anni, la versione onesta, non quella da Instagram.",
  "Chiedi al gruppo di descriverti con un film: il gruppo sceglie, tu devi accettare.",
  "Fai finta di essere il/la tuo/a migliore amico/a e parla di te in terza persona.",
  "Racconta il momento in cui hai capito cosa vuoi davvero dalla vita.",
  "Di' al gruppo qual è la cosa di cui ti fidi di più nella vita.",
  "Racconta un momento in cui hai fatto qualcosa di completamente fuori dal tuo carattere.",
  "Fai finta di essere un life coach per 60 secondi e dai un consiglio a ogni persona nel gruppo.",
  "Racconta come sei quando sei completamente stanco/a e senza filtri.",
  "Di' al gruppo qual è la cosa che fai meglio di tutti nella stanza, senza falsa modestia.",
  "Racconta la cosa più bella che tu abbia mai visto con i tuoi occhi.",
  "Fai una domanda al gruppo che non hai mai avuto il coraggio di fare.",
  "Di' qual è la cosa che non sopporti di te stesso/a ma che non riesci a cambiare.",
  "Racconta un momento in cui qualcuno ti ha sorpreso in modo bellissimo.",
  "Fai finta di scrivere un post su quello che è successo stasera e leggilo ad alta voce.",
  "Di' al gruppo la cosa che ammiri di più in ognuno, una frase per ciascuno.",
  "Racconta com'è la tua amicizia ideale, cosa ci deve essere per forza.",
  "Fai finta di essere un personaggio di un videogioco: qual è la tua abilità speciale?",
  "Di' al gruppo una cosa che vorresti imparare dagli altri qui presenti.",
  "Racconta il momento più bello che hai vissuto con un gruppo di amici.",
  "Fai una promessa al gruppo, qualcosa di concreto che farai entro un mese.",
  "Di' al gruppo qual è la cosa che ti fa sentire davvero a tuo agio con le persone.",
  "Racconta qualcosa di bello che è successo di recente e che non hai ancora condiviso con nessuno.",
  "Fai finta di scrivere il tuo necrologio, la versione divertente e sincera.",
  "Di' al gruppo qual è la cosa più importante che hai imparato sull'amicizia.",
] as const;

export const truthSpicy: readonly string[] = [];

export const dareSpicy: readonly string[] = [];

export const truthOrDarePrompts: Record<
  TruthOrDareMode,
  Record<TruthOrDarePromptType, readonly string[]>
> = {
  normal: {
    truth: truthNormal,
    dare: dareNormal,
  },
  spicy: {
    truth: truthSpicy,
    dare: dareSpicy,
  },
};
